services:
  schedula:
    container_name: schedula
    image: ghcr.io/veirt/schedula:latest
    environment:
      - TZ=Asia/Makassar
      - DISCORD_OAUTH_CLIENT_ID=
      - DISCORD_OAUTH_CLIENT_SECRET=
      - DISCORD_SERVER_ID=
      - DISCORD_OAUTH_REDIRECT_URI=
      - DISCORD_WEBHOOK_URL=
      - JWT_SECRET=
    volumes:
      - ./server/db:/app/db # db directory
    build: .
