version: "3.0"

services:
  server:
    container_name: schedula_server
    environment:
      - TZ=Asia/Makassar
      - DISCORD_OAUTH_CLIENT_ID=
      - DISCORD_OAUTH_CLIENT_SECRET=
      - DISCORD_SERVER_ID=
      - DISCORD_OAUTH_REDIRECT_URI=
      - DISCORD_WEBHOOK_URL=
      - JWT_SECRET=
    volumes:
      - ./server/db:/app/db # db directory
    build:
      context: server
  client:
    container_name: schedula_client
    ports:
      - 8490:80
    build:
      context: client
    depends_on:
      - server
