version: "3.0"

services:
  server:
    container_name: schedula_server
    environment:
      - DISCORD_OAUTH_CLIENT_ID=
      - DISCORD_OAUTH_CLIENT_SECRET=
      - DISCORD_SERVER_ID=
      - DISCORD_OAUTH_REDIRECT_URI=
      - JWT_SECRET=
    volumes:
      - ./server/db:/app/db # db directory
    build:
      context: server
  client:
    container_name: schedula_client
    ports:
      - 8490:80
    build:
      context: client
    depends_on:
      - server
  notifier:
    container_name: schedula_notifier
    environment:
      - TZ=Etc/UTC
      - SCHEDULE_API_URL=http://server:3000/api
      - DISCORD_WEBHOOK_URL=
    build:
      context: notifier
      dockerfile: Dockerfile
    depends_on:
      - server
